### ISSUE TITLE
Problem with PostGraphile --watch flag not updating schema on PostGres schema changes

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-server#39]
The `--watch` flag is supposed to make PostGraphile listen for changes to the postgres database schema and update its schema accordingly. However, this doesn't seem to be happening. I'm having to quit the PostGraphile server and re-launch it to get it to recognise the schema changes.

We are currently launching PostGraphile from the `post_graphile.sh` script, which executes the following command:

`npx postgraphile -c "postgres://postgres@localhost/tmf_app_manager" -C postgres --watch --enhance-graphiql --dynamic-json --cors --export-schema-graphql "database/schema.graphql" --append-plugins @graphile-contrib/pg-simplify-inflector,postgraphile-plugin-nested-mutations`

**Comment by nmadruga** [comment]
I was having a little research regarding this one today. It seems to me that keeping the postgraphile in a separated server is not worth, since we can't use some of the features that running it in the same fastify server as a middleware. In this link: https://www.graphile.org/postgraphile/usage-schema/ it explains how to start one. 
With the Postgraphile as a middleware that would be another endpoint on the server  would also allow us to use `watchPostGraphileSchema` which could be running the `insert_data.js` after receives that the schema update is finished.
