### ISSUE TITLE
Re-think and propose changes on the Review schema replacing join tables

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-server#52]

**Comment by CarlosNZ** [comment]
Here's my suggestion:
![Review_revised 5-10-20](https://user-images.githubusercontent.com/5456533/95032288-75aed880-0716-11eb-81d6-ce2ac3ebf515.png)
Basically, just got rid of the Join tables and moved the needed fields to their relevant tables. 

I won't start making any changes to the actual schema script until you guys are okay with this. So let me know if you see any potential problems. To me, it's more intuitive and the GraphQL trees would be more logical (otherwise you'd need to be thinking in terms of Joins in GraphQL queries, which goes against the point of a GraphQL abstraction).

Need to consider if we need a way to flag the "active" assignment. E.g. if one reviewer has been unassigned and a new reviewer assigned, do we edit the same record in `review_section_assignment`, delete the record and make a new one, or create a new record and flag it as the "Active" one?

@nmadruga @andreievg

**Comment by CarlosNZ** [comment]
Also, with the current schema, it's not possible to create a single CreateReview mutation that heirarchically creates the review and responses, etc. all at once.

**Comment by andreievg** [comment]
> Also, with the current schema, it's not possible to create a single CreateReview mutation that hierarchically creates the review and responses, etc. all at once.

I think we are moving away from it, since generating dynamic queries at runtime wouldn't play well with the way we are using GraphQL from front end

> Need to consider if we need a way to flag the "active" assignment. E.g. if one reviewer has been unassigned and a new reviewer assigned, do we edit the same record in review_section_assignment, delete the record and make a new one, or create a new record and flag it as the "Active" one?

Active flag sounds like the way to go (although it's something we should probably leave for first iteration of review implementation).

> Basically, just got rid of the Join tables and moved the needed fields to their relevant tables.

I like the duplication way, but I don't see a way to track of who commented/changed what (there probably is a way but nothing straight forward).  Happy to hear suggestions on that front btw

`Section grained review and assignment`

Was wondering, do we really need a way to comment per section ? Can a comment by review be sufficient ?

If that's the case we can simplify schema by removing review_section (and review_section_assignment). Assigner still chooses to assign by section, but internally we just work with review_question_assignment

I am attempting to summarise all review functionality here: https://github.com/openmsupply/application-manager-server/issues/88
