### ISSUE TITLE
External user registration - Resulting homepage layout

### ISSUE THREAD

**Issue by jagoje** [openmsupply/application-manager-server#689]

**Comment by jagoje** [comment]
### The home page once the user logs in after being registered in the system

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/88009219/159613299-392c167e-69b0-4e23-8038-bb8f8de86365.png">

**Comment by CarlosNZ** [comment]
FYI -- we can't currently localise template names as they're part of the template configuration, not the system. "Edit User Details" is a template name. 

I have a suggested system for template localisations, but we weren't going to implement it just yet as it adds more complexity.

Let's discuss on Friday. We can always hard-code that link in the menu to be a system string, but I'm keen to keep such things to an absolute minimum, otherwise it defeats the purpose of having a configurable system)

(Are we going to want to have localisable templates in general? If so, we'll need to look at adding that functionality, which will be a bit more dev work)

**Comment by nmadruga** [comment]
Besides the "Change language" I think everythink looks good now that I have entered the templates in Portuguese on snapshot `angola_2022_03_31`, should we close thiis issue? Maybe we can address the "Change language" string issue as part of https://github.com/openmsupply/application-manager-web-app/issues/1140

**Comment by nmadruga** [comment]
Closing after moving the missing string "Change language" to be done as part of issue https://github.com/openmsupply/application-manager-web-app/issues/1140
